# Generated by Django 3.1.7 on 2021-03-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemtitle', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=400)),
                ('website', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='')),
                ('product', models.CharField(max_length=20)),
            ],
        ),
    ]
