# Generated by Django 3.1.7 on 2021-03-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_tickets_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customfield_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customfieldname', models.CharField(max_length=20)),
                ('customfieldtype', models.CharField(max_length=20)),
                ('customfieldplaceholder', models.CharField(max_length=30)),
                ('customfieldfieldlength', models.CharField(max_length=15)),
                ('customfieldrequired', models.CharField(max_length=20)),
                ('customfieldstatus', models.CharField(max_length=20)),
            ],
        ),
    ]
