# Generated by Django 3.1.7 on 2021-03-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_customfield_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmenttitle', models.CharField(max_length=20)),
                ('departmentdescription', models.CharField(max_length=100)),
            ],
        ),
    ]
