# Generated by Django 3.1.7 on 2021-03-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_departments_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge_Base_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowlegebaseDepartment', models.CharField(max_length=20)),
                ('knowlegebasetitle', models.CharField(max_length=20)),
                ('knowlegebasedescription', models.CharField(max_length=100)),
                ('knowlegebaserequired', models.CharField(max_length=20)),
            ],
        ),
    ]
