# Generated by Django 3.1.7 on 2021-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_knowledge_base_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=20)),
                ('staffemail', models.CharField(max_length=40)),
                ('staffdepartment', models.CharField(max_length=20)),
                ('staffrole', models.CharField(max_length=20)),
                ('staffstatus', models.CharField(max_length=20)),
                ('staffpassword', models.CharField(max_length=16)),
            ],
        ),
    ]
