# Generated by Django 3.1.7 on 2021-03-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_users_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roletitle', models.CharField(max_length=20)),
                ('settingsrole', models.CharField(max_length=200)),
                ('frontendsettingsrole', models.CharField(max_length=200)),
                ('departmentssettingsrole', models.CharField(max_length=200)),
                ('knowledgesettingsrole', models.CharField(max_length=200)),
                ('staffsettingsrole', models.CharField(max_length=200)),
                ('usersettingsrole', models.CharField(max_length=200)),
            ],
        ),
    ]
