# Generated by Django 3.1.7 on 2021-03-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_tickets_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets_data',
            name='user',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickets_data',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Problem Files'),
        ),
    ]
